name: Code coverage tests

permissions:
  contents: read

on: [workflow_call, workflow_dispatch]

jobs:
  coverage:
    name: Run code coverage testing
    strategy:
      matrix:
        # The 'id' value for each job should be added to the 'carry-forward' string in the 'finish' job.
        include:
          - id: x64-generic
            runner: ubuntu-latest
            CMAKE_ARGS: -DOQS_DIST_BUILD=OFF -DOQS_OPT_TARGET=generic
    runs-on: ${{ matrix.runner }}
    container: openquantumsafe/ci-ubuntu-latest:latest
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install curl
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      - name: Configure
        run: |
          mkdir build && cd build && \
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DUSE_COVERAGE=ON ${{ matrix.CMAKE_ARGS }} .. && \
          cmake -LA -N ..
      - name: Build
        run: ninja
        working-directory: build
      - name: Run tests
        run: ninja run_tests
        working-directory: build
      - name: Run lcov
        run: lcov -d . -c -o lcov.info --exclude usr/lib
      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@v2.3.6
        with:
          flag-name: ${{ matrix.id }}
          parallel: true

  finish:
    needs: coverage
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Finish coveralls.io
        uses: coverallsapp/github-action@v2.3.6
        with:
          parallel-finished: true
          carry-forward: "x64-generic"
