name: Code coverage tests

permissions:
  contents: read

on: [workflow_call, workflow_dispatch]

jobs:
  coverage:
    name: Run code coverage testing
    strategy:
      matrix:
        runner:
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    container: openquantumsafe/ci-ubuntu-latest:latest
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install curl
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      - name: Configure
        run: mkdir build && cd build && cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DUSE_COVERAGE=ON .. && cmake -LA -N ..
      - name: Build
        run: ninja
        working-directory: build
      - name: Run tests
        run: ninja run_tests
        working-directory: build
      - name: Run lcov
        run: lcov -d . -c -o lcov.info --exclude usr/lib
      - name: Upload to coveralls.io
        uses: coverallsapp/github-action@v2.3.6
